accounts/urls.py
#Bilal Ma - Urls Accounts 

from django.urls import path
from . import views
from .views import CustomPasswordResetView, CustomPasswordResetDoneView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView

app_name = "accounts"

urlpatterns = [
    path ('login/', views.login_user, name = 'login'),
    path ('logout/', views.logout_user, name = 'logout'),
    path ('register/', views.register_user, name = 'register'),
    path('registration-success/', views.registration_success, name='registration_success'), 
   #Bilal ma - reset password : 
    path('password-reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    #Bilal ma - Change mots de passe ou pseudo, quand utilisateur est Co : 
    path('password-change/', views.change_password, name='change_password'),
    path('change-username/', views.change_username, name='change_username'),


]

catalogue/urls.py
"""reservations.catalogue URL Configuration
"""
# Imgs 
from django.conf import settings
from django.conf.urls.static import static
from catalogue.views import index as home_index  
from django.urls import path, include
from django.contrib import admin
# from django.urls import path, include
from . import views
from .views import *
from .views import show
# from django.contrib.auth import views as auth_views
from .views import payment

#EA-import pour rss
from .feed import LatestEntriesFeed

#EA PDF
from .utilPDF.artistPDF import artist_pdf
from .utilPDF.showPDF import show_pdf

#EA API
from rest_framework.urlpatterns import format_suffix_patterns
from .api.views import artist


app_name='catalogue'

urlpatterns = [
    path('', views.home.index, name='home_index'),
    #Bilal - Pour vu sur artist
    path('artist/', views.artist.index, name='artist_index'),
    path('artist/<int:artist_id>', views.artist.show, name='artist_show'),

    #path('artist/create/'),
    #path('artist/edit/<int:artist_id>'),
    #path('show/create/'),
    #path('show/edit/<int:show_id>'),

    #EA Version API fonction
    #path('artist/', artist.artist_list.),
    #path('artist/<int:artist_id>', artist.artist_detail),

    #EA Version API class
    path('api/artist/', artist.ArtistList.as_view()),
    path('api/artist/<int:artist_id>', artist.ArtistDetail.as_view()),

    #Bilal - Pour vu sur type
    #Edward - Pas nécessaire
    #path('type/', views.type.index, name='type_index'),
    #path('type/<int:type_id>', views.type.show, name='type_show'),

    #Bilal - Pour vu sur locality
    #Edward - Pas nécessaire
    #path('locality/', locality.ListeLocalitesView.as_view(), name='locality_index'),
    #path('locality/<int:pk>/', locality.DetailLocaliteView.as_view(), name='locality_show'),

    #Bilal - Pour vu sur Role
    #Edward - Pas nécessaire 
    #path('role/', views.role.index, name='role_index'),
	#path('role/<int:role_id>', views.role.show, name='role_show'),

    #Bilal - Pour vu sur location
    #Edward - pas nécessaire 
    #path('location/', views.location.index, name='location_index'),
	#path('location/<int:location_id>', views.location.show, name='location_show'),

    #Bilal - Pour vu sur show 
    # path('show/', views.show.index, name='show_index'),
    # path('show/<int:show_id>', views.show.show, name='show_show'),

    path('show/', views.show, name='show_index'),
    path('show/<int:show_id>/', views.show, name='show_show'),
    #Bilal Ma - Authentifaction dans accounts/ 
    #Bilal ma - Add au panier / Remove/ Del/ Add/ ..
    path('add_to_cart/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.view_cart, name='view_cart'), 
    path('remove_from_cart/<int:pk>/', remove_from_cart, name='remove_from_cart'),
    #Bilal ma -  pour passage au paiement
    path('payment/', views.make_payment, name='make_payment'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment/checkout_summary/', views.checkout_summary, name='checkout_summary'),
    path('order_history/', views.order_history, name='order_history'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),

    #Edward A - chemin du feed rss
    path('feed/', LatestEntriesFeed(), name='rssfeed'),
    #Edward A - Chemin provisoire pour test pdf
    path('artist/artist_pdf/', artist_pdf, name='artist_pdf'),
    path('show/show_pdf/', show_pdf, name='show_pdf'),
]

urlpatterns = format_suffix_patterns(urlpatterns)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservations/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('catalogue.urls')), 
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

catalogue/models/ArtistType.py
from django.db import models
from .artist import *
from .type import *

class ArtistType(models.Model):
    # Clé primaire
    id = models.BigAutoField(primary_key=True, verbose_name="ID_artiste-type")
    # Clé étrangère vers Artist
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, verbose_name="ID_artiste")
    # Clé étrangère vers Type
    type = models.ForeignKey(Type, on_delete=models.CASCADE, verbose_name="Fonction_artiste")

    def __str__(self):
        return self.artist.firstname +" "+ self.artist.lastname

    class Meta:
        db_table = "artiste_type"

catalogue/models/Cart.py
from django.db import models
from catalogue.models import Show

class Cart(models.Model):
    show = models.ForeignKey(Show, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} {self.show.title}(s) in your cart"

    def total_price(self):
        return self.quantity * self.show.price

catalogue/models/Order.py
# Bilal Ma - models/Order.py
from django.db import models
from django.contrib.auth.models import User
from catalogue.models import Show 

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    payment_method = models.CharField(max_length=100)
    payment_confirmed = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)
    # Champ pour stocker les identifiants des spectacles commandés et les quantités
    ordered_items = models.ManyToManyField(Show, through='OrderItem')

    def __str__(self):
        return f"Order #{self.id} - User: {self.user.username}, Total Amount: {self.total_amount}, Payment Method: {self.payment_method}"

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    show = models.ForeignKey(Show, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"OrderItem - Order: {self.order.id}, Show: {self.show.title}, Quantity: {self.quantity}"

catalogue/models/artist.py
# models artist
from django.db import models

#API Auth & Permissions (pygments)
from pygments.lexers import get_lexer_by_name
from pygments.formatters.html import HtmlFormatter
from pygments import highlight

class Artist(models.Model):
    #Clé primaire
    id = models.BigAutoField(primary_key=True, verbose_name="ID_artiste")
    firstname = models.CharField(max_length=60)
    lastname = models.CharField(max_length=60)

    #API Auth & Permissions
    #owner = models.ForeignKey('auth.User', related_name='artists', on_delete=models.CASCADE)
    #highlighted = models.TextField()

    def __str__(self):
        return self.firstname +" "+ self.lastname
    
    #def save(self, *args, **kwargs):
    #    super().save(*args, **kwargs)

    class Meta:
        db_table = "artists"

catalogue/models/artistTypeShow.py
from django.db import models
from .ArtistType import *
from .show import *

# Create your models here.
class ArtistTypeShow(models.Model):
	#Clé primaire
	id = models.BigAutoField(primary_key=True, verbose_name="ID_artiste-type-show")
	#Clé étrangère vers Artist
	artist_type = models.ForeignKey(ArtistType, on_delete=models.SET_NULL , null=True, verbose_name="ID_artiste-type")
	#Clé étrangère vers Show
	show = models.ForeignKey(Show, on_delete=models.SET_NULL , null=True, verbose_name="ID_spectacle")
	
	class Meta:
		db_table = "artiste_type_show"

	def __str__(self):
		return self.artist_type.artist.firstname +" "+ self.artist_type.artist.lastname

catalogue/models/artist_type.py
from django.db import models
from .artist import *
from .type import *

class Artist_type(models.Model):
    artist   = models.ForeignKey(Artist, on_delete=models.CASCADE)
    type    = models.ForeignKey(Type, on_delete=models.CASCADE)
    
    class Meta:
	    db_table = "artist_type"
  

catalogue/models/artist_type_show.py
from django.db import models
from .artist_type import *
from .show import *

class Artist_type_show(models.Model):
    artist_type   = models.ForeignKey(Artist_type, on_delete=models.CASCADE)
    show    = models.ForeignKey(Show, on_delete=models.CASCADE)
    
    class Meta:
	    db_table = "artist_type_show"    

catalogue/models/collaboration.py
from django.db import models
from .show import *
from .ArtistType import *


class Collaboration(models.Model):
    # Clé primaire
    id = models.BigAutoField(primary_key=True, verbose_name="ID_collaboration")
    # Clé étrangère vers ArtistType
    artist_type = models.ForeignKey(ArtistType, on_delete=models.CASCADE, verbose_name="Artiste_type")
    # Clé étrangère vers Show
    show = models.ForeignKey(Show, on_delete=models.CASCADE, verbose_name="Shows")

catalogue/models/locality.py
from django.db import models

class Locality(models.Model):
    #Clé primaire
    id = models.BigAutoField(primary_key=True, verbose_name="ID_localité")
    code_postal = models.CharField(unique=True ,max_length=12, verbose_name="Code postal")
    nom = models.CharField(unique=True, max_length=255, verbose_name="Nom de la localité")

    class Meta:
        db_table = "localities"
        verbose_name = "Localité"
        verbose_name_plural = "Localités"

    def __str__(self):
        return self.nom

catalogue/models/location.py
from django.db import models
from .locality import *

# Create your models here.
class Location(models.Model):
    # Clé primaire
    id = models.BigAutoField(primary_key=True, verbose_name="ID_lieu")
    # Clé étrangère vers Locality
    locality = models.ForeignKey(Locality, on_delete=models.SET_NULL, null=True, verbose_name='locations')
    slug = models.CharField(max_length=60, unique=True)
    designation = models.CharField(max_length=60)
    address = models.CharField(max_length=255)
    website = models.CharField(max_length=255, null=True)
    phone = models.CharField(max_length=30, null=True)
    
    class Meta:
        db_table = "locations"
    
    def __str__(self):
        return self.slug

catalogue/models/representation.py
from django.db import models
from .location import *
from .show import *

class Representation(models.Model):
	#Clé primaire
	id = models.BigAutoField(primary_key=True, verbose_name="ID_representation")
	#Clé étrangère vers Show
	show = models.ForeignKey(Show, on_delete=models.SET_NULL, null=True, verbose_name="ID_spectacle")
	when = models.DateTimeField
	#Clé étrangère vers Location
	location = models.ForeignKey(Location, on_delete=models.SET_NULL , null=True, verbose_name="ID_lieu")

	class Meta:
		db_table = "representations"
	
	def __str__(self):
		return self.show.slug

catalogue/models/representationUser.py
from django.db import models
from .representation import *
from .user import *

class RepresentationUser(models.Model):
    #Clé primaire
    id = models.BigAutoField(primary_key=True, verbose_name="ID_representation-user")
    #Clé étrangère vers Representation
    representation = models.ForeignKey(Representation, on_delete=models.SET_NULL, null=True, verbose_name="ID_representation")
    #Clé étrangère vers User
    user = models.ForeignKey(User, on_delete=models.SET_NULL , null=True, verbose_name="ID_user")
    places = models.IntegerField

    class Meta:
       db_table = "representation_user"
    
    def __str__(self):
        return self.user.firstname

catalogue/models/role.py
from django.db import models

class Role(models.Model):
    #Clé primaire
    id = models.BigAutoField(primary_key=True, verbose_name="ID_role")
    name = models.CharField(max_length=60, unique=True, verbose_name="Nom du rôle")

    class Meta:
        db_table = "roles"
        verbose_name = "Rôle"
        verbose_name_plural = "Rôles"

    def __str__(self):
        return self.name

catalogue/forms/paymentForm.py
# Bilal ma - Formulaires
from django import forms
from catalogue.models import Order

class PaymentForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['payment_method']

catalogue/api/views/artist.py
from catalogue.models import *
from ..serializers import *
from django.http import JsonResponse, Http404
from rest_framework.decorators import APIView
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
#for class using mixins
from rest_framework import mixins
from rest_framework import generics


#GENERIC CLASS
class ArtistList(generics.ListCreateAPIView):
    queryset = Artist.objects.all()
    serializer_class = ArtistSerializer


class ArtistDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Artist.objects.all()
    serializer_class = ArtistSerializer


#MIXIN CLASS
'''
class ArtistList(mixins.ListModelMixin, mixins.CreateModelMixin, generics.GenericAPIView):
    queryset = Artist.objects.all()
    serializer_class = ArtistSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)
    

class ArtistDetail(mixins.RetrieveModelMixin, mixins.UpdateModelMixin, mixins.DestroyModelMixin, generics.GenericAPIView):
    queryset = Artist.objects.all()
    serializer_class = ArtistSerializer

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)
'''


#CLASS
'''
class ArtistList(APIView):
    def get(self, request, format=None):
        artists = Artist.objects.all()
        serializer = ArtistSerializer(artists, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = ArtistSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class ArtistDetail(APIView):
    def get_object(self, pk):
        try:
            return Artist.objects.get(pk=pk)
        except Artist.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        snippet = self.get_object(pk)
        serializer = ArtistSerializer(snippet)
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        snippet = self.get_object(pk)
        serializer = ArtistSerializer(snippet, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        snippet = self.get_object(pk)
        snippet.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
'''

#FUNCTION
@api_view(['GET', 'POST'])
def artist_list(request):

    if request.method == 'GET':
        artists = Artist.objects.all()
        serializer = ArtistSerializer(artists, many=True)
        return JsonResponse({"artists": serializer.data})
    
    if request.metjod == 'POST':
       serializer = ArtistSerializer(data=request.data)
       if serializer.is_calid():
           serializer.save()
           return Response(serializer.data, status=status.HTTP_201_CREATED)
       
@api_view(['GET', 'PUT','DELETE'])
def artist_detail(request, id):

    try:
        artist = Artist.objects.get(pk=id)
    except Artist.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    
    if request.method =='GET':
        serializer = ArtistSerializer(artist)
        return Response(serializer.data)
    
    elif request.method == 'PUT':
        serializer = ArtistSerializer(artist, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        
    elif request.method == 'DELETE':
        artist.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

catalogue/api/views/artistType.py
from catalogue.models import *
from ..serializers import *
#for class using mixins
from rest_framework import generics


#GENERIC CLASS
class ArtistTypeList(generics.ListCreateAPIView):
    queryset = ArtistType.objects.all()
    serializer_class = ArtistTypeSerializer


class ArtistTypeDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = ArtistType.objects.all()
    serializer_class = ArtistTypeSerializer

catalogue/templates/cart/cart.html
<!--Bilal Ma -  Pour ajoter au panier   cart/cart.html  -->

{% extends 'layouts/base.html' %}
{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Votre panier</h1>

    <table class="table">
        
        <thead>
            <tr>
                <th scope="col">Spectacle</th>
                <th scope="col">Quantité</th>
                <th scope="col">Prix unitaire</th>
                <th scope="col">Prix total</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        
        <tbody>
            {% for item in cart %}
            <tr>
                <td>{{ item.title }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.price }} €</td>
                <td>{{ item.total_price }} €</td>
                <td class="d-flex align-items-center">
                    <form action="{% url 'catalogue:remove_from_cart' item.show.id %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="number" name="quantity" min="1" max="{{ item.quantity }}" value="1" class="form-control">
                            <button type="submit" class="btn btn-outline-danger ms-2" name="remove">Supprimer</button>
                            <button type="submit" class="btn btn-outline-success ms-2" name="add">Ajouter</button>
                        </div>
                    </form>            
                </td>

            </tr>
            {% endfor %}
            <tr>
                <td colspan="3"><strong>Total</strong></td>
                <td><strong>{{ cart.get_total_price }} €</strong></td>
                <td></td>
            </tr>
        </tbody>
    </table>

    <div class="d-flex justify-content-between">
        <a href="{% url 'catalogue:show_index' %}" class="btn btn-primary">Retour à la liste des spectacles</a>
        <form method="post" action="{% url 'catalogue:make_payment' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Procéder au paiement</button>
        </form>
        <a href="{% url 'catalogue:order_history' %}" class="btn btn-primary">Voir l'historique des commandes</a>
    </div>
</div>

<!-- CSS Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    
{% endblock %}

catalogue/templates/cart/checkout_summary.html
<!-- Bilal ma - cart/checkout_summary.html -->

<h1>Votre résumé de panier</h1>
<table>
    <thead>
        <tr>
            <th>Spectacle</th>
            <th>Quantité</th>
            <th>Prix unitaire</th>
            <th>Prix total</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart_items %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.price }} €</td>
            <td>{{ item.total_price }} €</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<form method="post" action="{% url 'catalogue:payment_success' %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Valider le paiement</button>
</form>

catalogue/templates/cart/order_detail.html
<!-- Template cart/order_detail.html -->

{% extends 'layouts/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="card">
        <div class="card-body">
            <h1 class="card-title">Détails de la commande #{{ order.id }}</h1>
            <h3 class="card-subtitle mb-4">Date de commande: {{ order.order_date }}</h3>
            <h3 class="card-subtitle mb-4">Total: {{ order.total_amount }} €</h3>
            <h3 class="card-subtitle mb-4">Méthode de paiement: {{ order.payment_method }}</h3>

            <h2>Articles commandés :</h2>
            <ul class="list-group mb-4">
                {% for order_item in order.orderitem_set.all %}
                <li class="list-group-item">
                    {{ order_item.show.title }} -
                    Quantité: {{ order_item.quantity }} -
                    Prix unitaire: {{ order_item.show.price }} €
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

<!-- CSS Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

{% endblock %}

catalogue/templates/cart/order_history.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Historique de vos commandes</h1>
    <ul class="list-group">
        {% for order in orders %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <a href="{% url 'catalogue:order_detail' order.id %}" class="text-decoration-none">Commande #{{ order.id }}</a>
            <span>Date: {{ order.order_date }}</span>
            <span>Total: {{ order.total_amount }} €</span>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

catalogue/templates/cart/payment_information.html
<!-- Bilal Ma - /payment_information.html -->

{% block content %}
<div class="container mt-5">
    <div class="row mb-5">
        <div class="col">
            <h1>Récapitulatif de la commande</h1>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Spectacle</th>
                        <th scope="col">Quantité</th>
                        <th scope="col">Prix unitaire</th>
                        <th scope="col">Prix total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart_items %}
                    <tr>
                        <td>{{ item.title }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.price }} €</td>
                        <td>{{ item.total_price }}</td> 
                    </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="3"><strong>Total</strong></td>
                        <td><strong>{{ total_price }} €</strong></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <h1>Informations de paiement</h1>
            <form method="post" action="{% url 'catalogue:make_payment' %}">
                {% csrf_token %}
                <div class="form-group">
                    <h2>Choisissez votre méthode de paiement :</h2>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" id="visa" name="payment_method" value="Visa">
                        <label class="form-check-label" for="visa">Carte Visa</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" id="maestro" name="payment_method" value="Maestro">
                        <label class="form-check-label" for="maestro">Carte Maestro</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" id="paypal" name="payment_method" value="Paypal">
                        <label class="form-check-label" for="paypal">Paypal</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" id="sur_place" name="payment_method" value="Sur place">
                        <label class="form-check-label" for="sur_place">Paiement sur place</label>
                    </div>
                </div>

                <!-- Formulaires de paiement spécifiques -->
                <div id="payment_form_visa" style="display: none;">
                    <!-- Formulaire de paiement Visa -->
                    <div class="form-group">
                        <input type="text" class="form-control" name="card_number" placeholder="Numéro de carte">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="expiry_date" placeholder="Date d'expiration">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="cvv" placeholder="CVV">
                    </div>
                </div>

                <div id="payment_form_paypal" style="display: none;">
                    <!-- Formulaire de paiement Paypal -->
                    <div class="form-group">
                        <input type="email" class="form-control" name="paypal_email" placeholder="Adresse email Paypal">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" name="paypal_password" placeholder="Mot de passe Paypal">
                    </div>
                </div>

                <div id="payment_form_sur_place" style="display: none;">
                    <!-- Formulaire pour le paiement sur place -->
                    <div class="form-group">
                        <input type="text" class="form-control" name="comment" placeholder="(facultatif)">
                    </div>
                </div>

                <!-- Bouton de soumission -->
                <button type="submit" class="btn btn-primary">Payer</button>
            </form>
        </div>
    </div>
</div>


<!-- CSS Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">


<!-- JavaScript Bootstrap (optionnel si vous utilisez des fonctionnalités JavaScript de Bootstrap) -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

<!-- Script pour afficher les formulaires de paiement correspondants -->
<script>
    document.querySelectorAll('input[type=radio][name=payment_method]').forEach(function(input) {
        input.addEventListener('change', function() {
            var method = this.value;
            document.querySelectorAll('[id^=payment_form_]').forEach(function(form) {
                if (form.id === 'payment_form_' + method.toLowerCase().replace(' ', '_')) {
                    form.style.display = 'block';
                } else {
                    form.style.display = 'none';
                }
            });
        });
    });
</script>


{% endblock %}

catalogue/templates/cart/payment_success.html
{% block content %}
<div class="container mt-5">
    <div class="card">
        <div class="card-body">
            <h1 class="card-title">Félicitations, votre paiement a été traité avec succès.</h1>
            <h2 class="card-subtitle mb-4">L'équipe Students-Icc vous remercie pour votre commande.</h2>

            <h3>Résumé de la commande :</h3>
            <ul class="list-group mb-4">
                <li class="list-group-item">Total : {{ order.total_amount }} €</li>
                <li class="list-group-item">Méthode de paiement : {{ order.payment_method }}</li>
            </ul>

            <a href="{% url 'catalogue:home_index' %}" class="btn btn-primary">Retour à la page d'accueil</a>
        </div>
    </div>
</div>

<!-- CSS Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

{% endblock %}